# ELASTICSEARCH INSTALL
- name: Add Elasticsearch apt key.
  apt_key:
    url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    state: present
- name: Add Elasticsearch repository.
  apt_repository:
    repo: 'deb https://artifacts.elastic.co/packages/{{ elasticsearch_version }}/apt stable main'
    state: present
    update_cache: true
- name: Install Elasticsearch
  package:
    name: "{{ elasticsearch_package }}"
    state: present

- name: Copy elasticsearch configuration.
  template:
    src: "configs/{{ elasticsearch_conf }}"
    dest: "/etc/elasticsearch/elasticsearch.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart elasticsearch

- name: start and enable service
  service:
    name: elasticsearch
    state: started
    enabled: yes

