# Install and start ufw
- name: Install ufw
  apt:
    pkg:
      - ufw
    update_cache: yes
    state: present

- name: ufw rule ssh
  ufw:
    rule: allow
    proto: tcp
    port: '22'

- name: ufw rule 
  ufw:
    state: enabled
    rule: allow
    proto: tcp
    port: '"{{ item }}"'
    src: 192.168.60.0/24
  with_items:
    - "{{ ufw_ports }}"

