---
- name: Create the nginx_exporter group
  group:
    name: nginx_exporter
    state: present
    system: true

- name: Create the nginx_exporter user
  user:
    name: nginx_exporter
    groups: nginx_exporter
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false
    home: /

- block:
    - name: Download nginx_exporter binary to local folder
      become: false
      get_url:
        url: "https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v{{ nginx_exporter_version }}/nginx-prometheus-exporter_{{ nginx_exporter_version }}_linux_{{ go_arch }}.tar.gz"
        dest: "/tmp/nginx_exporter-{{ nginx_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        mode: '0644'
      register: _download_binary
      until: _download_binary is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack nginx_exporter binary
      become: false
      unarchive:
        src: "/tmp/nginx_exporter-{{ nginx_exporter_version }}.linux-{{ go_arch }}.tar.gz"
        dest: "/tmp"
        creates: "/tmp/nginx_exporter-{{ nginx_exporter_version }}.linux-{{ go_arch }}/nginx-prometheus-exporter"
      delegate_to: localhost
      check_mode: false

    - name: Propagate nginx_exporter binaries
      copy:
        src: "/tmp/nginx-prometheus-exporter"
        dest: "{{ _nginx_exporter_binary_install_dir }}/nginx-prometheus-exporter"
        mode: 0755
        owner: root
        group: root
      notify: restart nginx_exporter
      when: not ansible_check_mode
  when: nginx_exporter_binary_local_dir | length == 0

- name: propagate locally distributed nginx_exporter binary
  copy:
    src: "{{ nginx_exporter_binary_local_dir }}/nginx-prometheus-exporter"
    dest: "{{ _nginx_exporter_binary_install_dir }}/nginx-prometheus-exporter"
    mode: 0755
    owner: root
    group: root
  when: nginx_exporter_binary_local_dir | length > 0
  notify: restart nginx_exporter


- name: create systemd service unit
  template:
    src: "{{ nginx_exporter_service_file }}"
    dest: /etc/systemd/system/nginx_exporter.service
    owner: root
    group: root
    mode: 0644
  notify:
    - restart nginx_exporter

- name: enable nginx_exporter.service
  service:
    name: nginx_exporter.service
    enabled: yes

- name: open node port for prometheus server
  ufw:
    state: enabled
    rule: allow
    proto: tcp
    port: '"{{ nginxE_port }}"'
    src: "{{ item }}"
  with_items:
    - '"{{ prometheus_ip }}"'
    - '"{{ host_ip }}"'

