---
- hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: Setup infrastructure
    become: false
    command:
      cmd: vagrant up
    delegate_to: localhost

  - debug:
      msg: "VMs UP"

  - name: cp hosts file to boxes
    copy:
      src: hosts
      dest: /etc/hosts
      owner: root
      group: root
      mode: 0644

- import_playbook: playbooks/nginx/nginx.yml
- import_playbook: playbooks/nginx/nginxP.yml
- import_playbook: playbooks/elk/elk.yml
- import_playbook: playbooks/prometheus/prometheus.yml
