---
- hosts: elk
  vars_files: vars_daemontools.yml
  become: true

  tasks:
    - name: install daemontools
      import_tasks: tasks/install_daemontools.yml

    - name: setup script 
      import_tasks: tasks/setup_script.yml

  handlers:
    - name: restart daemontools
      service:
        name: daemontools
        state: restarted
