---
# Setup nginx as webserver
- name: Nginx webserver
  hosts: nginx
  become: True
  vars_files: vars_nginx.yml


  tasks:
  - name: install and enable nginx
    import_tasks: tasks/nginx.yml
  - name: install and enable ufw
    import_tasks: tasks/ufw.yml
  - name: config nginx
    import_tasks: tasks/nginxConf.yml
  - name: install node exporter
    import_tasks: tasks/install_node.yml
  - name: install nginx exporter
    import_tasks: tasks/install_nginx_exporter.yml


  handlers:
  - name: restart_nginx
    service:
      name: nginx
      state: restarted

  - name: restart node_exporter
    systemd:
      daemon_reload: true
      name: node_exporter
      state: restarted

  - name: restart nginx_exporter
    systemd:
      daemon_reload: true
      name: nginx_exporter
      state: restarted

