global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus and node'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090', 'localhost:9100']
  - job_name: 'nginx webserver'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginx.test:9100','nginx.test:9113']
  - job_name: 'nginx caching proxy'
    scrape_interval: 5s
    static_configs:
      - targets: ['nginxP.test:9100','nginxP.test:9113']
  - job_name: 'elasticsearch'
    scrape_interval: 5s
    static_configs:
      - targets: ['elk.test:9114']
